// Package render executes credential-free inventory templates (REQ-E2-S03).
package render

import "time"

// RenderContext is the single data bag templates receive (template-contract §1).
// Templates never read files or the network.
type RenderContext struct {
	Manifest   EnvironmentRunManifest
	Docs       []InventoryDocument
	Upstream   map[string]UpstreamEntry
	Generation GenerationMeta
	Copy       map[string]string
}

// EnvironmentRunManifest records fresh/stale/missing for every source.
type EnvironmentRunManifest struct {
	EnvironmentID string
	Sources       []SourceOutcome
}

// SourceOutcome is one source's completeness outcome in a run.
type SourceOutcome struct {
	SourceID string
	Status   string // fresh | stale | missing
}

// UpstreamEntry is one catalogued upstream observation (may be empty map).
type UpstreamEntry struct {
	ObservedVersion string
	SourceURL       string
	Query           string
	RetrievedAt     time.Time
	Evidence        string
	Status          string
}

// GenerationMeta is render-time provenance for the autogenerated banner.
type GenerationMeta struct {
	GeneratedAt   time.Time
	Origin        string // schedule | manual | caller-supplied
	SnapshotSHA   string
	SourceRepoURL string
}

// InventoryDocument is a validated schema-v0 inventory document.
type InventoryDocument struct {
	SchemaVersion string             `yaml:"schemaVersion" json:"schemaVersion"`
	Metadata      DocumentMetadata   `yaml:"metadata" json:"metadata"`
	Provenance    DocumentProvenance `yaml:"provenance" json:"provenance"`
	TargetOutcomes []TargetOutcome   `yaml:"targetOutcomes" json:"targetOutcomes"`
	Components    []Component        `yaml:"components" json:"components"`
	HelmReleases  []HelmRelease      `yaml:"helmReleases" json:"helmReleases"`
	Workloads     []Workload         `yaml:"workloads" json:"workloads"`
	Nodes         NodesSummary       `yaml:"nodes" json:"nodes"`
}

// DocumentMetadata is the inventory metadata block.
type DocumentMetadata struct {
	EnvironmentID string      `yaml:"environmentId" json:"environmentId"`
	SourceID      string      `yaml:"sourceId" json:"sourceId"`
	CollectedAt   time.Time   `yaml:"collectedAt" json:"collectedAt"`
	Stale         *StaleMeta  `yaml:"stale,omitempty" json:"stale,omitempty"`
}

// StaleMeta marks a carry-forward document.
type StaleMeta struct {
	LastGoodAt time.Time `yaml:"lastGoodAt" json:"lastGoodAt"`
	StatusCode string    `yaml:"statusCode" json:"statusCode"`
}

// DocumentProvenance is the last-good run that produced the payload.
type DocumentProvenance struct {
	RunID                  string    `yaml:"runId" json:"runId"`
	CollectionStartedAt    time.Time `yaml:"collectionStartedAt" json:"collectionStartedAt"`
	CollectionFinishedAt   time.Time `yaml:"collectionFinishedAt" json:"collectionFinishedAt"`
	RawPayloadDigest       string    `yaml:"rawPayloadDigest" json:"rawPayloadDigest"`
	CollectorVersion       string    `yaml:"collectorVersion" json:"collectorVersion"`
	NormalizerVersion      string    `yaml:"normalizerVersion" json:"normalizerVersion"`
	ConfigVersion          string    `yaml:"configVersion" json:"configVersion"`
	SchemaDigest           string    `yaml:"schemaDigest" json:"schemaDigest"`
	TemplateVersion        string    `yaml:"templateVersion,omitempty" json:"templateVersion,omitempty"`
}

// TargetOutcome is one collection target's result.
type TargetOutcome struct {
	TargetID  string `yaml:"targetId" json:"targetId"`
	Status    string `yaml:"status" json:"status"`
	ErrorCode string `yaml:"errorCode,omitempty" json:"errorCode,omitempty"`
}

// Component is a named platform component instance.
type Component struct {
	ComponentID string `yaml:"componentId" json:"componentId"`
	InstanceID  string `yaml:"instanceId" json:"instanceId"`
	Name        string `yaml:"name" json:"name"`
	Kind        string `yaml:"kind,omitempty" json:"kind,omitempty"`
	Namespace   string `yaml:"namespace,omitempty" json:"namespace,omitempty"`
	Version     string `yaml:"version" json:"version"`
}

// HelmRelease is a deployed Helm release summary.
type HelmRelease struct {
	InstanceID   string `yaml:"instanceId" json:"instanceId"`
	ComponentID  string `yaml:"componentId" json:"componentId"`
	Name         string `yaml:"name" json:"name"`
	Namespace    string `yaml:"namespace" json:"namespace"`
	ChartName    string `yaml:"chartName" json:"chartName"`
	ChartVersion string `yaml:"chartVersion" json:"chartVersion"`
	AppVersion   string `yaml:"appVersion,omitempty" json:"appVersion,omitempty"`
	Status       string `yaml:"status" json:"status"`
}

// Workload is a workload container-image summary.
type Workload struct {
	Kind      string   `yaml:"kind" json:"kind"`
	Name      string   `yaml:"name" json:"name"`
	Namespace string   `yaml:"namespace" json:"namespace"`
	Images    []string `yaml:"images" json:"images"`
}

// NodesSummary aggregates node/Kubernetes versions.
type NodesSummary struct {
	Count          int      `yaml:"count" json:"count"`
	KubeVersions   []string `yaml:"kubeVersions" json:"kubeVersions"`
}
