package format

import (
	"fmt"
	"strings"

	"github.com/platformrelay/kollect-render/internal/render"
)

type confluenceEncoder struct{}

func (confluenceEncoder) Name() string { return NameConfluenceStorage }

func (confluenceEncoder) Encode(m Model) ([]byte, error) {
	var b strings.Builder
	for _, block := range m.Blocks {
		if err := writeConfluenceBlock(&b, block); err != nil {
			return nil, err
		}
	}
	return []byte(b.String()), nil
}

func writeConfluenceBlock(b *strings.Builder, block Block) error {
	switch v := block.(type) {
	case Heading:
		fmt.Fprintf(b, "<h%d>", v.Level)
		if v.Anchor != "" {
			b.WriteString(`<ac:structured-macro ac:name="anchor" ac:schema-version="1">`)
			fmt.Fprintf(b, `<ac:parameter ac:name="">%s</ac:parameter>`, escapeXML(v.Anchor))
			b.WriteString(`</ac:structured-macro>`)
		}
		b.WriteString(escapeXML(stripMDTicks(v.Text)))
		fmt.Fprintf(b, "</h%d>\n", v.Level)
	case Banner:
		b.WriteString(`<ac:structured-macro ac:name="panel" ac:schema-version="1" data-layout="default">`)
		b.WriteString(`<ac:parameter ac:name="bgColor">#DEEBFF</ac:parameter>`)
		b.WriteString(`<ac:parameter ac:name="borderColor">#0747A6</ac:parameter>`)
		b.WriteString(`<ac:parameter ac:name="title">AUTO-GENERATED — do not edit manually</ac:parameter>`)
		b.WriteString(`<ac:rich-text-body>`)
		fmt.Fprintf(b,
			`<p>Autogenerated at <code>%s</code> (%s) · origin <code>%s</code> · `+
				`<a href="%s/commit/%s">snapshot</a></p>`,
			escapeXML(v.GeneratedAt),
			escapeXML(v.GeneratedDate),
			escapeXML(v.Origin),
			escapeXML(v.SourceRepoURL),
			escapeXML(v.SnapshotSHA),
		)
		fmt.Fprintf(b, `<p>%s</p>`, escapeXML(v.HowToChange))
		b.WriteString(`<p>`)
		writeStatusMacro(b, "Blue", "AUTOGENERATED")
		writeStatusMacro(b, "Red", "DO NOT EDIT")
		b.WriteString(`</p>`)
		b.WriteString(`</ac:rich-text-body></ac:structured-macro>`)
		b.WriteByte('\n')
	case StatusLegend:
		b.WriteString(`<p><strong>Status legend:</strong></p>`)
		b.WriteString(`<table data-layout="default"><tbody>`)
		b.WriteString(`<tr><th><p>Status</p></th><th><p>Meaning</p></th></tr>`)
		writeLegendRow(b, "Green", "Ready", "Ready/current")
		writeLegendRow(b, "Yellow", "Warning", "warning/minor/stale")
		writeLegendRow(b, "Red", "NotReady", "NotReady/major")
		writeLegendRow(b, "Grey", "Unknown", "unknown")
		b.WriteString(`</tbody></table>`)
		b.WriteByte('\n')
	case Paragraph:
		b.WriteString("<p>")
		if err := writeConfluenceInlines(b, v.Inlines); err != nil {
			return err
		}
		b.WriteString("</p>\n")
	case BulletList:
		b.WriteString("<ul>\n")
		for _, item := range v.Items {
			b.WriteString("<li><p>")
			if err := writeConfluenceInlines(b, item); err != nil {
				return err
			}
			b.WriteString("</p></li>\n")
		}
		b.WriteString("</ul>\n")
	case Table:
		b.WriteString(`<table data-layout="default"><tbody>`)
		b.WriteString("<tr>")
		for _, h := range v.Headers {
			fmt.Fprintf(b, "<th><p>%s</p></th>", escapeXML(h))
		}
		b.WriteString("</tr>")
		for _, row := range v.Rows {
			b.WriteString("<tr>")
			for _, cell := range row {
				fmt.Fprintf(b, "<td><p>%s</p></td>", escapeXML(cell))
			}
			b.WriteString("</tr>")
		}
		b.WriteString("</tbody></table>\n")
	case Blank:
		// no-op in storage format
	case CapNote:
		fmt.Fprintf(b, "<p>%s</p>\n", escapeXML(render.CapNote(true, v.N)))
	case Footnote:
		fmt.Fprintf(b, "<p><em>%s</em></p>\n", escapeXML(v.Text))
	default:
		return fmt.Errorf("confluence-storage: unsupported block %T", block)
	}
	return nil
}

func writeConfluenceInlines(b *strings.Builder, inlines []Inline) error {
	for _, in := range inlines {
		switch v := in.(type) {
		case Text:
			b.WriteString(escapeXML(v.S))
		case Strong:
			fmt.Fprintf(b, "<strong>%s</strong>", escapeXML(v.S))
		case Code:
			fmt.Fprintf(b, "<code>%s</code>", escapeXML(v.S))
		case Link:
			fmt.Fprintf(b, `<a href="%s">%s</a>`, escapeXML(v.URL), escapeXML(v.Text))
		case Emoji:
			b.WriteString(escapeXML(v.S))
		default:
			return fmt.Errorf("confluence-storage: unknown inline %T (no raw-safe bypass)", in)
		}
	}
	return nil
}

func writeStatusMacro(b *strings.Builder, colour, title string) {
	fmt.Fprintf(b,
		`<ac:structured-macro ac:name="status" ac:schema-version="1">`+
			`<ac:parameter ac:name="colour">%s</ac:parameter>`+
			`<ac:parameter ac:name="title">%s</ac:parameter></ac:structured-macro>`,
		escapeXML(colour), escapeXML(title),
	)
}

func writeLegendRow(b *strings.Builder, colour, title, meaning string) {
	b.WriteString("<tr><td><p>")
	writeStatusMacro(b, colour, title)
	b.WriteString("</p></td>")
	fmt.Fprintf(b, "<td><p>%s</p></td></tr>", escapeXML(meaning))
}

func escapeXML(s string) string {
	replacer := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
	)
	return replacer.Replace(s)
}

func stripMDTicks(s string) string {
	return strings.ReplaceAll(s, "`", "")
}
