package format

import (
	"strings"
	"testing"
)

func TestWriteBannerEmitsPanelMacro(t *testing.T) {
	t.Parallel()
	var b strings.Builder
	writeBanner(&b, Banner{
		GeneratedAt: "2026-07-21T05:00:00Z", GeneratedDate: "2026-07-21",
		Origin: "manual", SourceRepoURL: "https://example.org/r", SnapshotSHA: "abc",
		HowToChange: "edit upstream",
	})
	s := b.String()
	for _, want := range []string{
		`ac:name="panel"`,
		"AUTO-GENERATED",
		"2026-07-21T05:00:00Z",
		"https://example.org/r/commit/abc",
		"edit upstream",
		"AUTOGENERATED",
		"DO NOT EDIT",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("writeBanner missing %q in:\n%s", want, s)
		}
	}
}

func TestWriteStatusLegendEmitsTable(t *testing.T) {
	t.Parallel()
	var b strings.Builder
	writeStatusLegend(&b)
	s := b.String()
	for _, want := range []string{
		"<strong>Status legend:</strong>",
		"Ready/current",
		"warning/minor/stale",
		"NotReady/major",
		"unknown",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("writeStatusLegend missing %q in:\n%s", want, s)
		}
	}
}
