package format

import (
	"fmt"
	"strings"

	"github.com/platformrelay/kollect-render/internal/render"
)

type markdownEncoder struct{}

func (markdownEncoder) Name() string { return NameMarkdown }

func (markdownEncoder) Encode(m Model) ([]byte, error) {
	var b strings.Builder
	for _, block := range m.Blocks {
		if err := writeMarkdownBlock(&b, block); err != nil {
			return nil, err
		}
	}
	return []byte(b.String()), nil
}

func writeMarkdownBlock(b *strings.Builder, block Block) error {
	switch v := block.(type) {
	case Heading:
		prefix := strings.Repeat("#", v.Level)
		if v.Anchor != "" {
			fmt.Fprintf(b, "%s %s {#%s}\n", prefix, v.Text, v.Anchor)
		} else {
			fmt.Fprintf(b, "%s %s\n", prefix, v.Text)
		}
	case Banner:
		fmt.Fprintf(b, "> Autogenerated at %s (%s) · origin %s · [%s](%s/commit/%s)\n",
			v.GeneratedAt, v.GeneratedDate, v.Origin, "snapshot", v.SourceRepoURL, v.SnapshotSHA)
		b.WriteString(">\n")
		fmt.Fprintf(b, "> %s\n", v.HowToChange)
	case StatusLegend:
		b.WriteString("**Status legend:** ")
		b.WriteString(render.StatusEmoji("Ready"))
		b.WriteString(" Ready/current · ")
		b.WriteString(render.StatusEmoji("warning"))
		b.WriteString(" warning/minor/stale · ")
		b.WriteString(render.StatusEmoji("NotReady"))
		b.WriteString(" NotReady/major · ")
		b.WriteString(render.StatusEmoji("unknown"))
		b.WriteString(" unknown\n")
	case Paragraph:
		writeMarkdownInlines(b, v.Inlines)
		b.WriteByte('\n')
	case BulletList:
		for _, item := range v.Items {
			b.WriteString("- ")
			writeMarkdownInlines(b, item)
			b.WriteByte('\n')
		}
	case Table:
		b.WriteString("| ")
		b.WriteString(strings.Join(v.Headers, " | "))
		b.WriteString(" |\n| ")
		seps := make([]string, len(v.Headers))
		for i := range seps {
			seps[i] = "---"
		}
		b.WriteString(strings.Join(seps, " | "))
		b.WriteString(" |\n")
		for _, row := range v.Rows {
			b.WriteString("| ")
			b.WriteString(strings.Join(row, " | "))
			b.WriteString(" |\n")
		}
	case Blank:
		b.WriteByte('\n')
	case CapNote:
		b.WriteString(render.CapNote(true, v.N))
		b.WriteByte('\n')
	case Footnote:
		fmt.Fprintf(b, "_%s_\n", v.Text)
	default:
		return fmt.Errorf("markdown: unsupported block %T", block)
	}
	return nil
}

func writeMarkdownInlines(b *strings.Builder, inlines []Inline) {
	for _, in := range inlines {
		switch v := in.(type) {
		case Text:
			b.WriteString(v.S)
		case Strong:
			b.WriteString("**")
			b.WriteString(v.S)
			b.WriteString("**")
		case Code:
			b.WriteByte('`')
			b.WriteString(v.S)
			b.WriteByte('`')
		case Link:
			fmt.Fprintf(b, "[%s](%s)", v.Text, v.URL)
		case Emoji:
			b.WriteString(v.S)
		}
	}
}
