// Package format is the compile-time output-format registry (REQ-E2-S04).
package format

// Model is a format-agnostic rendered page. Encoders turn the same Model into
// markdown or confluence-storage bytes (REQ-E2-S04-01). There is no raw-safe
// bypass: all string content is contextually escaped by the encoder.
type Model struct {
	Blocks []Block
}

// Block is one top-level page element.
type Block interface {
	block()
}

// Banner is the mandatory autogenerated preamble (template-contract §3).
type Banner struct {
	GeneratedAt   string // RFC3339 UTC
	GeneratedDate string // YYYY-MM-DD
	Origin        string
	SourceRepoURL string
	SnapshotSHA   string
	HowToChange   string
}

func (Banner) block() {}

// StatusLegend is the fixed status-emoji legend line.
type StatusLegend struct{}

func (StatusLegend) block() {}

// Heading is a section heading; Anchor is optional (markdown {#id} / confluence anchor).
type Heading struct {
	Level  int
	Text   string
	Anchor string
}

func (Heading) block() {}

// Paragraph is a single paragraph of inline runs.
type Paragraph struct {
	Inlines []Inline
}

func (Paragraph) block() {}

// BulletList is an unordered list; each item is a sequence of inline runs.
type BulletList struct {
	Items [][]Inline
}

func (BulletList) block() {}

// Table is a simple header + row table (confluence uses native tables; markdown uses pipes).
type Table struct {
	Headers []string
	Rows    [][]string
}

func (Table) block() {}

// Blank is a blank line between blocks.
type Blank struct{}

func (Blank) block() {}

// CapNote is the "list capped at n entries" note.
type CapNote struct {
	N int
}

func (CapNote) block() {}

// Footnote is italic trailing copy (health disclaimer).
type Footnote struct {
	Text string
}

func (Footnote) block() {}

// Inline is a text run inside a paragraph or list item.
type Inline interface {
	inline()
}

// Text is plain text (escaped by encoders as needed).
type Text struct{ S string }

func (Text) inline() {}

// Strong is bold text.
type Strong struct{ S string }

func (Strong) inline() {}

// Code is monospace text.
type Code struct{ S string }

func (Code) inline() {}

// Link is a hyperlink.
type Link struct {
	Text string
	URL  string
}

func (Link) inline() {}

// Emoji is a status glyph from the helper set (already a safe symbol).
type Emoji struct{ S string }

func (Emoji) inline() {}
